### ISSUE TITLE
example for usage?

### ISSUE THREAD

**Issue by kruegge82** [dreipunktnull/dhl-express#3]
Hello is there a example for usage?
thanks kruegge

**Comment by cedricziel** [comment]
There is an example in the README, no?

**Comment by kruegge82** [comment]
yes but no example with data to fill. How must the variable $sender, or $recipient be filled?

**Comment by cedricziel** [comment]
These need to be objects of `ContactInfoType`, as type-hinted.

**Comment by kruegge82** [comment]
its not working for me: Class 'ContactInfoType' not found, i have installed via composer an load include autoload.php....
thats why i asked for a example with setted values...

**Comment by cedricziel** [comment]
> `Class 'ContactInfoType' not found, i have installed via composer an load include autoload.php....

Perfectly fine question. Which version do you use and did you add use-statements to import the class?

**Comment by kruegge82** [comment]
im using version 2.0.2, and as i told using autoloader.php so normaly i dont need use-statement...
but ok if i use the use statements he found the classes... but next problem he dont found the class 'ShipmentRequest', and in the src-gen folder there is no ShipmentRequest.php

i try 'ProcessShipmentRequestType' but so i get this error:
Uncaught TypeError: Argument 4 passed to ShipmentRequestService::createShipping() must be an instance of ShipmentRequest, instance of DHL\Express\Webservice\ProcessShipmentRequestType given

**Comment by cedricziel** [comment]
I recommmend you to look up what autoloading really does - I'm pretty sure it doesnt work how you think it does ;)

The Readme states: `You should therefore create your own ShipmentRequest data class` - the `ShipmentRequest` class is really just a DTO ensuring type-safe communication of the required data points.

**Comment by kruegge82** [comment]
It is really a pity, but unfortunately that does not work for me. Therefore, it would have been helpful to get a functioner of the example. Then I look for another solution.

The DHL SDK package from Pechko was much better explained, sorry

**Comment by cedricziel** [comment]
It's alright, no worries :) - Maybe this library is just not a good fit for you.

Pechkos package is for DHL, not DHL Express though, IIRC.

**Comment by bjo3rnf** [comment]
Closed due to lack of response
