### ISSUE TITLE
WssWsuAuthHeader

### ISSUE THREAD

**Issue by thomasphansen** [dreipunktnull/dhl-express#4]
Hello,
Thank you for the nice library! I have two questions for you, if you have the time:

The WssWsuAuthHeader defines a constructor and a static method. Both "seems" to do the same thing, but only the static method is used in your examples. Also, while the constructor "digests" the $nonce, $pass and $ts variables into a base64-encoded sha1 hash, the static method just adds them to a SimpleXMLElement (there is actually a variable - $passdigest - holding the digested value, but it is never used).
So, the questions are:

1. Do both work, or is the constructor version a leftover from previous versions?
2. If both work, is there any case where I should use one instead of the other?

Thank you for your time! Have a nice day! :)

(BTW, it could be nice to mention in the documentation that you used the wsdl2phpgenerator library to create the base code... :) )

**Comment by cedricziel** [comment]
To be honest - the part with the Authentication Header was the one thing that took the longest in all the library. We're solely using the static method. - So yes, maybe the constructor can go.

I hope that answers your questions ;)

You're right - I added a mention (https://github.com/dreipunktnull/dhl-express#acknowledgements). Thanks for pointing this out.

**Comment by thomasphansen** [comment]
Perfect, Cedric! Thanks for the info! Have a nice day! :)

**Comment by cedricziel** [comment]
Have a nice day as well!
