### ISSUE TITLE
Example 

### ISSUE THREAD

**Issue by potsdamnights** [dreipunktnull/dhl-express#7]
Hey liebes DreiPunktNull-Team,
 
ich habe auf Github ihre DHL Express php API gefunden. Das ist echt eine gute Sache. Ich konnte sie auch per Composer  erstellen.
Könnt ihr mir das so zur Verfügung stellen, das ich einen Sender, Empfänger, die Zugangsdaten (ggf. Labeltype) eintrage und ein Label zurück bekomme.
Ich blicke da noch nicht ganz durch. Oder gibt es dafür ein Example?

**Comment by bjo3rnf** [comment]
Hi,

sorry, but this project is somewhat abandoned and we are not able to support it any longer. 

Cheers
Björn
